branch:	ARTXX-00-01-04-main-00 (main trunk) rev:	ARTXX-00-01-04-main-00-68-merged-parser-04-06
  Merged -parser-04 branch to make import mechanism work.
	Featuring completely reentrant lexers and parsers.
	Validated against bison-1.35 -2.0, yacc, flex-2.5.4, -2.5.31.

diff --git a/test/artc-expect.sh.in b/test/artc-expect.sh.in
--- a/test/artc-expect.sh.in
+++ b/test/artc-expect.sh.in
@@ -1,6 +1,6 @@
 #!@SH_PATH@
 # "artc-expect.sh.in"
-#	$Id: artc-expect.sh.in,v 1.4 2005/11/10 02:13:12 fang Exp $
+#	$Id: artc-expect.sh.in,v 1.5 2005/11/12 08:45:36 fang Exp $
 # This file came from "artc-expect.sh" in revision pre-history.
 
 # $1 is the executable, expecting input from stdin ("hackt parse_test")
@@ -31,30 +31,33 @@ logfile=$5
 $cmd < $srcroot.in > $bldroot.test 2>&1
 if [ $? -gt 1 ] ; then exit 1 ; fi
 @CAT@ $bldroot.test | $filter > $bldroot.test.filter
-if [ -f $srcroot.stderr ] && ! [ -f $bldroot.stderr ] ; then
-	@LN_S@ $srcroot.stderr $bldroot.stderr
+if [ -f $srcroot.stderr ] ; then
+	@DIFF@ -bu $srcroot.stderr $bldroot.test.filter > $bldroot.diff 2>&1
+elif [ -f $bldroot.stderr ] ; then
+	# this would've been created by the Makefile automatically
+	@DIFF@ -bu $bldroot.stderr $bldroot.test.filter > $bldroot.diff 2>&1
 else
-	@TOUCH@ $bldroot.stderr
+	@ECHO@ "Missing $srcroot.stderr." > $bldroot.diff
 fi
 
-@DIFF@ -bu $bldroot.stderr $bldroot.test.filter > $bldroot.diff 2>&1
 
 # first-try: if different, see if it's because of bison...
 # if so, re-run using bison's expected output
 # otherwise, exit with error
+# there will never be $bldroot.stderr.bison 
+# (meaning: empty, and generated by Makefile)
 @HAVE_BISON_TRUE@if [ -s $bldroot.diff ] ; then
-@HAVE_BISON_TRUE@	if [ -f $srcroot.stderr.bison ] && \
-@HAVE_BISON_TRUE@			! [ -f $bldroot.stderr.bison ] ; then
-@HAVE_BISON_TRUE@		@LN_S@ $srcroot.stderr.bison $bldroot.stderr.bison
-@HAVE_BISON_TRUE@	else
-@HAVE_BISON_TRUE@		@TOUCH@ $bldroot.stderr.bison
-@HAVE_BISON_TRUE@	fi
-@HAVE_BISON_TRUE@	@DIFF@ -bu $bldroot.stderr.bison $bldroot.test.filter \
+@HAVE_BISON_TRUE@	if [ -f $srcroot.stderr.bison ] ; then
+@HAVE_BISON_TRUE@	@DIFF@ -bu $srcroot.stderr.bison $bldroot.test.filter \
 @HAVE_BISON_TRUE@		> $bldroot.bison.diff 2>&1
-@HAVE_BISON_TRUE@	if ! [ -s $bldroot.bison.diff ] ; then
-@HAVE_BISON_TRUE@		mv -f $bldroot.bison.diff $bldroot.diff
+@HAVE_BISON_TRUE@		if ! [ -s $bldroot.bison.diff ] ; then
+@HAVE_BISON_TRUE@			mv -f $bldroot.bison.diff $bldroot.diff
+@HAVE_BISON_TRUE@		else
+@HAVE_BISON_TRUE@			@ECHO@ "$bldroot.bison.diff is non-empty!"
+@HAVE_BISON_TRUE@		fi
 @HAVE_BISON_TRUE@	else
-@HAVE_BISON_TRUE@		@ECHO@ "$bldroot.bison.diff is non-empty!"
+@HAVE_BISON_TRUE@		@ECHO@ "Missing $srcroot.stderr.bison."
+@HAVE_BISON_TRUE@		exit 1;
 @HAVE_BISON_TRUE@	fi
 @HAVE_BISON_TRUE@fi
 
